# syntax=docker/dockerfile:1

FROM golang:1.21.4

# Set destinaton for COPY
WORKDIR /app

# Download Go modules
COPY go.mod go.sum ./
RUN go mod download && go mod verify

# Copy the source code
COPY ./ ./

# Set default port the app will listen on
EXPOSE 8080

# Run
CMD [ "go", "run", "./cmd/curio-qa-api/main.go" ]
