# docker-compose version, more on: https://docs.docker.com/compose/compose-file/compose-versioning/
version: "3.8"

services:
  mongo:
    container_name: mongo
    image: mongo:7.0.3
    ports:
      - 27017:27017
    networks:
      - curio_qa_api_network
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    command: mongod

  redis:
    container_name: redis
    image: redis:7.2.3
    ports:
      - 6379:6379
    networks:
      - curio_qa_api_network
    volumes:
      - redis_cache:/data
  
  curio_qa_api:
    container_name: curio_qa_api
    image: curio_qa_api:1.0
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    networks:
      - curio_qa_api_network
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - mongo

networks:
  curio_qa_api_network:
    name: curio_qa_api_network

volumes:
  mongo_data:
    name: "mongo_data"
  mongo_config:
    name: "mongo_config"
  redis_cache:
    name: "redis_cache"
