# syntax=docker/dockerfile:1

FROM golang:1.21.4

# Set destinaton for COPY
WORKDIR /app

# Download Go modules
COPY go.mod go.sum ./
RUN go mod download && go mod verify

# Copy the source codes
COPY ./ ./

# Run go unit tests
RUN go test -v ./...

# Build executable
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build ./cmd/curio-qa-api

# Set default port the app will listen on
EXPOSE 8080

# Run
CMD [ "./curio-qa-api" ]
